/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CourseManager {
      
    export type CourseStruct = {id: BigNumberish, author: AddressLike, price: BigNumberish, isActive: boolean}

    export type CourseStructOutput = [id: bigint, author: string, price: bigint, isActive: boolean] & {id: bigint, author: string, price: bigint, isActive: boolean }
  
    }

  export interface CourseManagerInterface extends Interface {
    getFunction(nameOrSignature: "COURSE_CREATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "buyCourse" | "courseBalances" | "courseEthBalances" | "courseNFT" | "coursePurchasers" | "courses" | "createCourse" | "getCourse" | "getRoleAdmin" | "grantRole" | "hasRole" | "paymentToken" | "renounceRole" | "revokeRole" | "supportsInterface" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CourseCreated" | "CoursePurchased" | "CourseWithdraw" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'COURSE_CREATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyCourse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'courseBalances', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'courseEthBalances', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'courseNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'coursePurchasers', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'courses', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCourse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCourse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'COURSE_CREATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courseBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courseEthBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courseNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coursePurchasers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace CourseCreatedEvent {
      export type InputTuple = [courseId: BigNumberish, author: AddressLike, price: BigNumberish];
      export type OutputTuple = [courseId: bigint, author: string, price: bigint];
      export interface OutputObject {courseId: bigint, author: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CoursePurchasedEvent {
      export type InputTuple = [courseId: BigNumberish, buyer: AddressLike];
      export type OutputTuple = [courseId: bigint, buyer: string];
      export interface OutputObject {courseId: bigint, buyer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CourseWithdrawEvent {
      export type InputTuple = [courseId: BigNumberish, author: AddressLike, amount: BigNumberish];
      export type OutputTuple = [courseId: bigint, author: string, amount: bigint];
      export interface OutputObject {courseId: bigint, author: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CourseManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): CourseManager;
    waitForDeployment(): Promise<this>;

    interface: CourseManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COURSE_CREATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyCourse: TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    courseBalances: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    courseEthBalances: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    courseNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    coursePurchasers: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    courses: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, boolean] & {id: bigint, author: string, price: bigint, isActive: boolean }],
      'view'
    >
    

    
    createCourse: TypedContractMethod<
      [price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getCourse: TypedContractMethod<
      [courseId: BigNumberish, ],
      [CourseManager.CourseStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COURSE_CREATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyCourse'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'courseBalances'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'courseEthBalances'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'courseNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'coursePurchasers'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'courses'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, boolean] & {id: bigint, author: string, price: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'createCourse'): TypedContractMethod<
      [price: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCourse'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [CourseManager.CourseStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CourseCreated'): TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
getEvent(key: 'CoursePurchased'): TypedContractEvent<CoursePurchasedEvent.InputTuple, CoursePurchasedEvent.OutputTuple, CoursePurchasedEvent.OutputObject>;
getEvent(key: 'CourseWithdraw'): TypedContractEvent<CourseWithdrawEvent.InputTuple, CourseWithdrawEvent.OutputTuple, CourseWithdrawEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'CourseCreated(uint256,address,uint256)': TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
      CourseCreated: TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
    

      'CoursePurchased(uint256,address)': TypedContractEvent<CoursePurchasedEvent.InputTuple, CoursePurchasedEvent.OutputTuple, CoursePurchasedEvent.OutputObject>;
      CoursePurchased: TypedContractEvent<CoursePurchasedEvent.InputTuple, CoursePurchasedEvent.OutputTuple, CoursePurchasedEvent.OutputObject>;
    

      'CourseWithdraw(uint256,address,uint256)': TypedContractEvent<CourseWithdrawEvent.InputTuple, CourseWithdrawEvent.OutputTuple, CourseWithdrawEvent.OutputObject>;
      CourseWithdraw: TypedContractEvent<CourseWithdrawEvent.InputTuple, CourseWithdrawEvent.OutputTuple, CourseWithdrawEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }