/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AAVEAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AAVEAdapter__factory>
getContractFactory(name: 'IAavePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAavePool__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'CourseManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CourseManager__factory>
getContractFactory(name: 'CourseNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CourseNFT__factory>
getContractFactory(name: 'RewardPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardPool__factory>
getContractFactory(name: 'YIDENGToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.YIDENGToken__factory>
getContractFactory(name: 'MockAavePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAavePool__factory>
getContractFactory(name: 'MockWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockWETH__factory>

  getContractAt(name: 'AAVEAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AAVEAdapter>
getContractAt(name: 'IAavePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAavePool>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'CourseManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CourseManager>
getContractAt(name: 'CourseNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CourseNFT>
getContractAt(name: 'RewardPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardPool>
getContractAt(name: 'YIDENGToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.YIDENGToken>
getContractAt(name: 'MockAavePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAavePool>
getContractAt(name: 'MockWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockWETH>

  deployContract(name: 'AAVEAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AAVEAdapter>
deployContract(name: 'IAavePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAavePool>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'CourseManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CourseManager>
deployContract(name: 'CourseNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CourseNFT>
deployContract(name: 'RewardPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardPool>
deployContract(name: 'YIDENGToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.YIDENGToken>
deployContract(name: 'MockAavePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAavePool>
deployContract(name: 'MockWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>

  deployContract(name: 'AAVEAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AAVEAdapter>
deployContract(name: 'IAavePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAavePool>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'CourseManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CourseManager>
deployContract(name: 'CourseNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CourseNFT>
deployContract(name: 'RewardPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardPool>
deployContract(name: 'YIDENGToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.YIDENGToken>
deployContract(name: 'MockAavePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAavePool>
deployContract(name: 'MockWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  