/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockAavePoolInterface extends Interface {
    getFunction(nameOrSignature: "supplied" | "supply" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Supplied" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'supplied', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supply', values: [AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'supplied', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace SuppliedEvent {
      export type InputTuple = [asset: AddressLike, onBehalfOf: AddressLike, amount: BigNumberish];
      export type OutputTuple = [asset: string, onBehalfOf: string, amount: bigint];
      export interface OutputObject {asset: string, onBehalfOf: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [asset: AddressLike, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [asset: string, user: string, amount: bigint];
      export interface OutputObject {asset: string, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockAavePool extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockAavePool;
    waitForDeployment(): Promise<this>;

    interface: MockAavePoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    supplied: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    supply: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, arg3: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, to: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'supplied'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supply'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, arg3: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, to: AddressLike, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'Supplied'): TypedContractEvent<SuppliedEvent.InputTuple, SuppliedEvent.OutputTuple, SuppliedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Supplied(address,address,uint256)': TypedContractEvent<SuppliedEvent.InputTuple, SuppliedEvent.OutputTuple, SuppliedEvent.OutputObject>;
      Supplied: TypedContractEvent<SuppliedEvent.InputTuple, SuppliedEvent.OutputTuple, SuppliedEvent.OutputObject>;
    

      'Withdrawn(address,address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }